### PR TITLE
Add possibility to choose destination "changes" instead of "Tickets".

### PR DESCRIPTION
**Pull request by goshiz**

### CODE REVIEW

**Comment by btry** [comment]
Hi 

I attempted to update this branch without regressions : https://github.com/btry/formcreator/tree/add_target_change

**Comment by goshiz** [comment]
Ok. Thanks !

I will try to update to this branch.

Gaël.



2016-11-15 19:03 GMT+01:00 btry <notifications@github.com>:

**Comment by btry** [comment]
Hi 

I may create a PR from my branch to your fork. However I think I'll still update things in a few weeks to prepare a merge (many developments are WIP and will affect your contribution, planned after the next release)

**Comment by btry** [comment]
Recent changes needs update of this PR; see #368 for a up to date equivalent

**Pull request closed without merging**
