### PR TITLE
move user area above the services

### PR DESCRIPTION
**Pull request by btry**
The left menu looks like this with these changes

image

I believe there is still something to do to give a better look and feel before merging

### CODE REVIEW

**Comment by orthagh** [comment]
I think placing entities/profiles under user shoud be better

**Comment by btry** [comment]
A try with your request gives this

image

I think this may be better to move the entity / profile selectors after the menu like  this, because these will be mainly used by power ful users (form designers ?), and this will allow a rendering ig the service catalog closer to the end users experience. Example below

image

**Comment by orthagh** [comment]
Ok for entity/profiles selector.

I'm not convinced with the current proposal for others parts.
Maybe we can try to integrate icons and user photo/name on the same line as the logo (with breakings lines for some parts)

**Comment by orthagh** [comment]
For Bookmarks, an idea (an old one, in fact): maybe we could offer a full page (and a dedicated text menu on the same level as issues).

**Comment by btry** [comment]
Here is a draft showing my curent orientation about the user avatar and buttons

image

However, I wonder where to show the user name. Maybe under the avatar, aligned to the right of the blue area.

I removed bookmarks because the 3 buttons needs too much height. I'm considering moving the bookmarks as a main menu item.

**Comment by orthagh** [comment]
Maybe i missed to push it, but previously, i changed the user (awesome-) icon for real avatar as we have it in glpi fs ?

You removed it or i didn't push id ?

**Comment by btry** [comment]
I guess you didn't pushed it : I tried to update ma branche a few minutes before pushing my latest changes, and I was up to date

**Comment by orthagh** [comment]
ok :D

**Pull request merged**
