### PR TITLE
Add full SLA/OLA support in target

### PR DESCRIPTION
**Pull request by AdrienClairembault**
Internal ref: 19538.

Add new options in targets to set service levels (SLA and OLA) or directly the expected dates (TTO, internal TTO, TTR and external TTR).
Full details regarding these new options can be found in the internal ref.

### CODE REVIEW

**Comment by AdrienClairembault** [comment]
Unit tests seems to ignore 2_11 migration changes, not sure why.

**Comment by btry** [comment]
I'll run then locally with your branch to find out the problem.

**Comment by btry** [comment]
I think I found the problem @AdrienClairembault 

you added upgrade code, but you did not updated the SQL script for fresh installation. Because of that, there is a difference of schema between a fresh installation and an upgrade.

**Comment by AdrienClairembault** [comment]
Can we merge if I drop the due_dates changes and keep the sla/ola part as discussed ?

**Comment by btry** [comment]
Hi

Shall the plugin convert due dates into SLA ? This would allow us to drop due date.

**Comment by AdrienClairembault** [comment]
I think we need to keep the due date (maybe deprecated it ?).
It can't always be replaced by SLA (e.g. DUE_DATE_RULE_ANSWER).

I'll put it back in if it's ok for you (the "new" internal_due_date, take_into_account_date and internal_take_into_account_date  are still removed).

**Comment by AdrienClairembault** [comment]
Ready for review

**Comment by btry** [comment]
Hi @AdrienClairembault 

I rebased and updated your PR to satisfy unit  tests.

Please have a review and if it is OK for you, merge it and ping me. I have a refactor PR to apply next (#1873)

**Comment by AdrienClairembault** [comment]
ping @btry

**Pull request merged**
