### PR TITLE
twig question edition

### PR DESCRIPTION
**Pull request by btry**
linked to https://github.com/glpi-project/glpi/pull/10806

Contains commits to fix the unit tests witrh the font awesome dropdown.

### CODE REVIEW

**Comment by AdrienClairembault** [comment]
Fatal error when trying to create a form.
```
[2022-03-09 08:23:03] glpiphplog.WARNING:   *** PHP Warning (2): require_once(/home/adrie/localhost/gmaster/plugins/formcreator/data/font-awesome.php): failed to open stream: No such file or directory in /home/adrie/localhost/gmaster/plugins/formcreator/inc/common.class.php at line 163
  Backtrace :
  plugins/formcreator/inc/common.class.php:163       require_once()
  plugins/formcreator/inc/common.class.php:185       PluginFormcreatorCommon::getFontAwesomePictoNames()
  :                                                  PluginFormcreatorCommon::showFontAwesomeDropdown()
  src/Application/View/Extension/PhpExtension.php:85 call_user_func_array()
  ...84ea8622aa41ad549b5756dfe913c807d009d2e.php:672 Glpi\Application\View\Extension\PhpExtension->call()
  .../twig/twig/src/Extension/CoreExtension.php:1202 __TwigTemplate_25957d626dee4ca2fe453cdd9b7686542575e78b7df9188f608ab9b15c04b5e6->macro_dropdownFontAwesomeIconField()
  ...670342208f4670a50cfd50dd75ce6417467c355.php:110 twig_call_macro()
  vendor/twig/twig/src/Template.php:171              __TwigTemplate_f6eea49aa00b4008200f535b2fd98b4c6c48067bd5fae8bf31555bf1936d2823->block_form_fields()
  ...5c392594dcef9acab55e084b7c69cb97b3cfc735.php:95 Twig\Template->displayBlock()
  vendor/twig/twig/src/Template.php:394              __TwigTemplate_ec2b85923481f3745d18dde30c385bdeb872fff58dc5419f114e20691438af8c->doDisplay()
  vendor/twig/twig/src/Template.php:367              Twig\Template->displayWithErrorHandling()
  ...c670342208f4670a50cfd50dd75ce6417467c355.php:47 Twig\Template->display()
  vendor/twig/twig/src/Template.php:394              __TwigTemplate_f6eea49aa00b4008200f535b2fd98b4c6c48067bd5fae8bf31555bf1936d2823->doDisplay()
  vendor/twig/twig/src/Template.php:367              Twig\Template->displayWithErrorHandling()
  vendor/twig/twig/src/TemplateWrapper.php:47        Twig\Template->display()
  src/Application/View/TemplateRenderer.php:177      Twig\TemplateWrapper->display()
  plugins/formcreator/inc/form.class.php:438         Glpi\Application\View\TemplateRenderer->display()
  src/CommonGLPI.php:655                             PluginFormcreatorForm->showForm()
  ajax/common.tabs.php:107                           CommonGLPI::displayStandardTab()
```

Did you forget to commit `data/font-awesome.php` ?
Or was it deleted but you forgot some references to it ?

**Comment by AdrienClairembault** [comment]
Fatal error when trying to create a form.
```
[2022-03-09 08:23:03] glpiphplog.WARNING:   *** PHP Warning (2): require_once(/home/adrie/localhost/gmaster/plugins/formcreator/data/font-awesome.php): failed to open stream: No such file or directory in /home/adrie/localhost/gmaster/plugins/formcreator/inc/common.class.php at line 163
  Backtrace :
  plugins/formcreator/inc/common.class.php:163       require_once()
  plugins/formcreator/inc/common.class.php:185       PluginFormcreatorCommon::getFontAwesomePictoNames()
  :                                                  PluginFormcreatorCommon::showFontAwesomeDropdown()
  src/Application/View/Extension/PhpExtension.php:85 call_user_func_array()
  ...84ea8622aa41ad549b5756dfe913c807d009d2e.php:672 Glpi\Application\View\Extension\PhpExtension->call()
  .../twig/twig/src/Extension/CoreExtension.php:1202 __TwigTemplate_25957d626dee4ca2fe453cdd9b7686542575e78b7df9188f608ab9b15c04b5e6->macro_dropdownFontAwesomeIconField()
  ...670342208f4670a50cfd50dd75ce6417467c355.php:110 twig_call_macro()
  vendor/twig/twig/src/Template.php:171              __TwigTemplate_f6eea49aa00b4008200f535b2fd98b4c6c48067bd5fae8bf31555bf1936d2823->block_form_fields()
  ...5c392594dcef9acab55e084b7c69cb97b3cfc735.php:95 Twig\Template->displayBlock()
  vendor/twig/twig/src/Template.php:394              __TwigTemplate_ec2b85923481f3745d18dde30c385bdeb872fff58dc5419f114e20691438af8c->doDisplay()
  vendor/twig/twig/src/Template.php:367              Twig\Template->displayWithErrorHandling()
  ...c670342208f4670a50cfd50dd75ce6417467c355.php:47 Twig\Template->display()
  vendor/twig/twig/src/Template.php:394              __TwigTemplate_f6eea49aa00b4008200f535b2fd98b4c6c48067bd5fae8bf31555bf1936d2823->doDisplay()
  vendor/twig/twig/src/Template.php:367              Twig\Template->displayWithErrorHandling()
  vendor/twig/twig/src/TemplateWrapper.php:47        Twig\Template->display()
  src/Application/View/TemplateRenderer.php:177      Twig\TemplateWrapper->display()
  plugins/formcreator/inc/form.class.php:438         Glpi\Application\View\TemplateRenderer->display()
  src/CommonGLPI.php:655                             PluginFormcreatorForm->showForm()
  ajax/common.tabs.php:107                           CommonGLPI::displayStandardTab()
```

Did you forget to commit `data/font-awesome.php` ?
Or was it deleted but you forgot some references to it ?

**Review by AdrienClairembault — CHANGES_REQUESTED** [review]
1\) The question's description isn't aligned with the rest of the form

image

2\) The question modal closes itself randomly.
Not sure what you can do about this as it hard to reproduce but maybe the event that trigger the modal to close could be reduced as a first step ? 
IMO it should only close when clicking the "X" button, pressing "esc" or successfully submitting the form.
This means clicking outside the modal shouldn't close it for example.

3\) I can't add a "float" question:
image

Also as a side note, "Float" isn't the best label.
Programmers talk about floating point numbers but others people simply refer to them as decimal numbers ;)

4\) Same error for integers:
image

5\) I can still create "Tag" questions without having the Tag plugin activated
image

6\) Can't create a "Text" question:
image

7\) Same for "Textarea"

**Comment by btry** [comment]
1) The question's description isn't aligned with the rest of the form

No solution found, this annoys me as well

2) The question modal closes itself randomly.
Not sure what you can do about this as it hard to reproduce but maybe the event that trigger the modal to close could be reduced as a first step ?
IMO it should only close when clicking the "X" button, pressing "esc" or successfully submitting the form.
This means clicking outside the modal shouldn't close it for example.

Behaviours seen on GLPI's core (tested on dashboard creation)
- Pressing ESC no longer works with GLPI 10.
- clicking outside the modal closes the form with core's modal 

I need more description of the remaining cases, if any.

3) 4) 6) 7) Probably missing parameters to configure a  float, integer, textarea or text. I'll double check against v2.12.

5), will double check against 2.12.

**Comment by btry** [comment]
5) fixed. 

3, 4 6

**Comment by btry** [comment]
With versions 2.12 it is possible to create a tags question when the  tags plugin is not enabled. Deciding if we should disallow creation of such question is out of scope of this PR.

**Review by AdrienClairembault — CHANGES_REQUESTED** [review]
There is still some misaligned stuff: 

image

image

**Comment by btry** [comment]
fixed 
image

image

**Review by AdrienClairembault — APPROVED** [review]

**Pull request merged**
