### PR TITLE
Code refactor for target ticket and target change

### PR DESCRIPTION
**Pull request by btry**

### CODE REVIEW

**Comment by btry** [comment]
Still 2 warnings to solve

```
2017-04-26 08:46:46 [2@workstation-sid]
  *** PHP Notice(8): Undefined index: rolloutplancontent
  Backtrace :
  plugins/formcreator/inc/targetchange.class.php:927 
  plugins/formcreator/inc/form_answer.class.php:845  PluginFormcreatorTargetChange->save()
  plugins/formcreator/inc/form_answer.class.php:690  PluginFormcreatorForm_Answer->generateTarget()
  plugins/formcreator/inc/form.class.php:1129        PluginFormcreatorForm_Answer->saveAnswers()
  plugins/formcreator/front/form.form.php:90         PluginFormcreatorForm->saveForm()
2017-04-26 08:46:46 [2@workstation-sid]
  *** PHP Notice(8): Undefined index: backoutplancontent
  Backtrace :
  plugins/formcreator/inc/targetchange.class.php:931 
  plugins/formcreator/inc/form_answer.class.php:845  PluginFormcreatorTargetChange->save()
  plugins/formcreator/inc/form_answer.class.php:690  PluginFormcreatorForm_Answer->generateTarget()
  plugins/formcreator/inc/form.class.php:1129        PluginFormcreatorForm_Answer->saveAnswers()
  plugins/formcreator/front/form.form.php:90         PluginFormcreatorForm->saveForm()
```

**Comment by orthagh** [comment]
Note sure if its related, Here is some errors found when updating to this branch:

```
2017-05-03 09:16:48 [27@LU002]
  *** PHP Notice(8): Undefined variable: tablename
  Backtrace :
  ...ins/formcreator/install/update_0.0_2.5.php:1131 
  plugins/formcreator/install/update_0.0_2.5.php:25  plugin_formcreator_updateTargetChange()
  plugins/formcreator/install/install.php:41         plugin_formcreator_update_2_5()
  plugins/formcreator/hook.php:17                    PluginFormcreatorInstall->upgrade()
  inc/plugin.class.php:693                           plugin_formcreator_install()
  front/plugin.form.php:48                           Plugin->install()
```

```
2017-05-03 09:16:48 [27@LU002]
  *** MySQL query error:
  SQL: SELECT COUNT(*) AS `cpt` FROM (SELECT DISTINCT
                  NULL                           AS `id`,
                  CONCAT(\'f_\',`fanswer`.`id`)    AS `display_id`,
                  `fanswer`.`id`                 AS `original_id`,
                  \'PluginFormcreatorForm_Answer\' AS `sub_itemtype`,
                  `f`.`name`                     AS `name`,
                  `fanswer`.`status`             AS `status`,
                  `fanswer`.`request_date`       AS `date_creation`,
                  `fanswer`.`request_date`       AS `date_mod`,
                  `fanswer`.`entities_id`        AS `entities_id`,
                  `fanswer`.`is_recursive`       AS `is_recursive`,
                  `fanswer`.`requester_id`       AS `requester_id`,
                  `fanswer`.`validator_id`       AS `validator_id`,
                  `fanswer`.`comment`            AS `comment`
               FROM `glpi_plugin_formcreator_forms_answers` AS `fanswer`
               LEFT JOIN `glpi_plugin_formcreator_forms` AS `f`
                  ON`f`.`id` = `fanswer`.`plugin_formcreator_forms_id`
               LEFT JOIN `glpi_items_tickets` AS `itic`
                  ON `itic`.`items_id` = `fanswer`.`id`
                  AND `itic`.`itemtype` = \'PluginFormcreatorForm_Answer\'
               WHERE `fanswer`.`is_deleted` = \'0\'
               GROUP BY `original_id`
               HAVING COUNT(`itic`.`tickets_id`) != 1

               UNION

               SELECT DISTINCT
                  NULL                          AS `id`,
                  CONCAT(\'t_\',`tic`.`id`)       AS `display_id`,
                  `tic`.`id`                    AS `original_id`,
                  \'Ticket\'                      AS `sub_itemtype`,
                  `tic`.`name`                  AS `name`,
                  `tic`.`status`                AS `status`,
                  `tic`.`date`                  AS `date_creation`,
                  `tic`.`date_mod`              AS `date_mod`,
                  `tic`.`entities_id`           AS `entities_id`,
                  0                             AS `is_recursive`,
                  `tic`.`users_id_recipient`    AS `requester_id`,
                  0                             AS `validator_id`,
                  `tic`.`content`               AS `comment`
               FROM `glpi_tickets` AS `tic`
               LEFT JOIN `glpi_items_tickets` AS `itic`
                  ON `itic`.`tickets_id` = `tic`.`id`
                  AND `itic`.`itemtype` = \'PluginFormcreatorForm_Answer\'
               WHERE `tic`.`is_deleted` = 0
               GROUP BY `original_id`
               HAVING COUNT(`itic`.`items_id`) <= 1) AS `issues`
  Error: Unknown column 'fanswer.is_deleted' in 'where clause'
  Backtrace :
  plugins/formcreator/inc/issue.class.php:89         
  plugins/formcreator/install/update_0.0_2.5.php:387 PluginFormcreatorIssue::cronSyncIssues()
  plugins/formcreator/install/update_0.0_2.5.php:20  plugin_formcreator_updateIssue()
  plugins/formcreator/install/install.php:41         plugin_formcreator_update_2_5()
  plugins/formcreator/hook.php:17                    PluginFormcreatorInstall->upgrade()
  inc/plugin.class.php:693                           plugin_formcreator_install()
  front/plugin.form.php:48                           Plugin->install()
```

**Comment by orthagh** [comment]
Anothers:

```
2017-05-03 09:40:36 [27@LU002]
  *** PHP Notice(8): Undefined index: rolloutplancontent
  Backtrace :
  plugins/formcreator/inc/targetchange.class.php:233 
  inc/commonglpi.class.php:472                       PluginFormcreatorTargetChange->showForm()
  ajax/common.tabs.php:96                            CommonGLPI::displayStandardTab()
2017-05-03 09:40:36 [27@LU002]
  *** PHP Notice(8): Undefined index: backoutplancontent
  Backtrace :
  plugins/formcreator/inc/targetchange.class.php:243 
  inc/commonglpi.class.php:472                       PluginFormcreatorTargetChange->showForm()
  ajax/common.tabs.php:96                            CommonGLPI::displayStandardTab()
```

- rolloutplancontent -> rolloutplancontext
- backoutplancontent -> backoutplancontext

**Comment by btry** [comment]
The following error should be fixed now
```
2017-05-03 09:16:48 [27@LU002]
  *** PHP Notice(8): Undefined variable: tablename
  Backtrace :
  ...ins/formcreator/install/update_0.0_2.5.php:1131 
  plugins/formcreator/install/update_0.0_2.5.php:25  plugin_formcreator_updateTargetChange()
  plugins/formcreator/install/install.php:41         plugin_formcreator_update_2_5()
  plugins/formcreator/hook.php:17                    PluginFormcreatorInstall->upgrade()
  inc/plugin.class.php:693                           plugin_formcreator_install()
  front/plugin.form.php:48                           Plugin->install()
```

**Comment by btry** [comment]
rebased due to collation cleanup

**Pull request merged**
