### PR TITLE
fix(question): filtering out tag question type broken

### PR DESCRIPTION
**Pull request by btry**
validated by the reporter

### CODE REVIEW

**Comment by phamorais** [comment]
Hi @btry the Type of question "TAGS" was removed from FORMS 2.6.3?

**Comment by btry** [comment]
Hi

No it is still there. But this type of question depends on the plugin Tags. If you have both enabled but this type of question is broken, please open an issue.

**Comment by btry** [comment]
I remember I fixed a bug long ago related to this type of question when the plugin Tags is not enabled. Formcreator must check that Tags is enabled before showing such questions. Install and enable Tags and your problem shall vanish.

**Comment by phamorais** [comment]
Thank you, I'll test and position you.

**Comment by phamorais** [comment]
@btry after install the plugin TAG, its works! Thaaankou!

**Pull request merged**
