### PR TITLE
WIP Remove abusive encoding

### LINKED ISSUE #1019: It does not hide question descrition type.
It does not hide question descrition type.
Following examples screens.

screenshot-2018-6-19 chamado nti - forms - 5

screenshot-2018-6-19 chamado nti - forms - 5 1

### PR DESCRIPTION
**Pull request by btry**
remove all HTML entities in question definitions

see #1006 #851 #848 

closes #1019

### CODE REVIEW

**Comment by Synairgis** [comment]
1) Create a selectbox with values "L'école" and "L'Hòpital".
2) Create a second question which should be visible when "L'école" is selected
3) Create a third question which is standard text with a max length of 5
4) Enter a text too long in the third question and submit the form

When you return to the form, the second question is hidden even though it shouldn't be.

**Comment by Synairgis** [comment]
With the latest patch, I've identified two more problems with the exact same conditions as before. 

1) Just load the form and immediately, the third control gets hidden even though the value in the current list is "L'école", which means it should be visible

2) Choose "L'hòpital" as a value in the list and submit the form with a text too long in the second question. When you return to the form, the selectbox's value is back to "L'école".

**Comment by btry** [comment]
The changes of the last commits introduces some regression. I'll notify you when the branch will  be stable enough for tests.

**Comment by btry** [comment]
I worked hard to finish my plans to migrate unit tests from phpunit to atoum. This PR requires tests, and I want to add tests in Atoum instead of phpunit, to avoid rewrrite for Atoum (double work). 

Migration to Atoum will be merged in 2.7.0-dev, then this PR too.

**Comment by btry** [comment]
Hi @Synairgis 

I added a commit which fixes the 1st scenario you described here. It seems the 2nd is solved also.

Do you want to test it and feedback ? With your double check, I may consider to merge this PR for 2.6.4.

This PR must be tested without your custom patches to avoid conflicts.

**Comment by btry** [comment]
PR osbolete

**Pull request closed without merging**
