### PR TITLE
Issue #662 - Multiple files upload

### PR DESCRIPTION
**Pull request by lbteles**
Issue #662 - Multiple files upload

### CODE REVIEW

**Comment by lbteles** [comment]
Hi!

It seems the code I changed is breaking PHPCode Sniffer rules, but only on PHP 7.2 and Nightly.
Could anyone look into it? :)

Thanks!

**Comment by btry** [comment]
Hi

I guess the CS isseus are caused by your IDE. Maybe it automatically reformatted the source code, but GLPI uses its own coding style convention.

**Comment by lbteles** [comment]
How do I format the code according to GLPI?

**Comment by btry** [comment]
Hi

Here are the coding standards : http://glpi-developer-documentation.readthedocs.io/en/master/codingstandards.html

**Comment by lbteles** [comment]
I've done the code formatting fixes. Looks like everything's okay. I could not understand the mistakes that occurred in the last two Travis jobs.

**Comment by btry** [comment]
Hi

One of the jobs failed because the plugin uses some methods being deprecated very recently in GLPI 9.3 (in development).

I just finished to replace all these calls.

Please rebase your contribution on the branch develop, and these errors should vanish.

Not checked y et, but maybe some CS errors are still there...

**Pull request closed without merging**
