### PR TITLE
Feature/external tools

### PR DESCRIPTION
**Pull request by trasher**

### CODE REVIEW

**Comment by btry** [comment]
It invalidates #434 (because it uses the new tools package). 

The first commit of this PR is obviously OK, but the 2 last fixing CS may cause conflicts with the #480 .

**Comment by trasher** [comment]
The second commit is just an automated run of phpbf from the `robo code:cs` call; this is quite simple to cancel an run again.
The last one is manual changes, but there are only a few ones, even if it conflits something, it should not be a huge one.

**Comment by btry** [comment]
@trasher : did you intentionnaly add composer.lock in the PR ?

**Comment by btry** [comment]
#519 merged ! finally ! (and invalidates this one)

**Pull request closed without merging**
