### PR TITLE
add category question

### PR DESCRIPTION
**Pull request by btry**
with background code refactor on urgency

### CODE REVIEW

**Comment by orthagh** [comment]
Some comments:
- Add an option to set the category manually without template and question. We aim, i think, to drop template option or minimise it to the minimum (set to final ticket for hidden fields)
- As we have now PluginFormcreatorTargetChange, maybe we should think about a Target Super class with common code (in another pr)

**Comment by orthagh** [comment]
And fix travis build :)

**Comment by btry** [comment]
Added ability to set a specific value for category. For a better consistency, I added the same feature for urgency.

**Comment by orthagh** [comment]
Seems good. Last comment and it will be ok i think.
Could you ordering the fields like this:
- Entity
- Ticket template | Due Date
- Category
- Urgency

**Comment by btry** [comment]
You missed the Tags section. Where do you want to see it in your list ?

**Comment by orthagh** [comment]
last one, didn't saw it because the plugin isn't enabled in my side.

**Pull request merged**
