### PR TITLE
fix show / hide select field

### PR DESCRIPTION
**Pull request by btry**
Fix HTML entities problem with select fields which should show or hide on condfition when a form is displayed

### CODE REVIEW

**Comment by btry** [comment]
Fix validated by the reporter of the issue.

**Comment by orthagh** [comment]
ok for the reporter.
This is particulary hard to review because i'm can't be sure these sort of fixes could not break some other parts, you see.

**Comment by btry** [comment]
I agree that's why I want to remove all these string escaping mess and rewrite the evaluation system nicely numbered #666

**Comment by orthagh** [comment]
:D good timing

**Pull request merged**
