### PR TITLE
Add form visibility setting

### PR DESCRIPTION
**Pull request by AdrienClairembault**
### Changes description

Add a new "Visible" setting to forms.
If this setting is disabled, the form wont be visible in the wizard but can still be accessed directly through its URL.

### Checklist

Please check if your PR fulfills the following specifications:

- [ ] Tests for the changes have been added
- [ ] Docs have been added/updated

### References

!22487

Closes #N/A

### CODE REVIEW

**Comment by AdrienClairembault** [comment]
Correct me if I'm wrong but tests failure doesn't seem related to these changes.

**Review by btry — CHANGES_REQUESTED** [review]
You need to update export and import unit tests. There is also a fixture form containing al types of questions. This is an export JSON, then it must be updated with the new field.

The code itself is ok.

**Comment by btry** [comment]
> Correct me if I'm wrong but tests failure doesn't seem related to these changes

Ys, the failures are not related to your code. I'm searching the solution as it occurs in other branches.That said if the tests to export / import a form don't complain with your new code, this is unusual, this is quite strange.

**Comment by AdrienClairembault** [comment]
My bad I didn't see the export part in the CI results, only this output which I though was unrelated:
image

**Pull request merged**
