### PR TITLE
remove file drop area on textarea field

### PR DESCRIPTION
**Pull request by btry**
finally found how to properly handle the uploads in textarea without showing the file drop zone.

### CODE REVIEW

**Comment by stonebuzz** [comment]
after add new textarea type, question is not display here
image

see counter on tab
```
[2020-02-04 14:08:09] glpisqllog.ERROR: DBmysql::query() in /home/stanislas/Teclib/dev/GLPI/9.4-bugfixes/inc/dbmysql.class.php line 188
  *** MySQL query error:
  SQL: SELECT `order` FROM `glpi_plugin_formcreator_questions` WHERE `plugin_formcreator_sections_id` = '2' ORDER BY `order` DESC LIMIT 1
  Error: Unknown column 'order' in 'field list'
  Backtrace :
  inc/dbmysqliterator.class.php:95                   
  inc/dbmysql.class.php:580                          DBmysqlIterator->execute()
  plugins/formcreator/inc/common.class.php:119       DBmysql->request()
  plugins/formcreator/inc/question.class.php:416     PluginFormcreatorCommon::getMax()
  inc/commondbtm.class.php:1098                      PluginFormcreatorQuestion->prepareInputForAdd()
  plugins/formcreator/front/question.form.php:50     CommonDBTM->add()
  {"user":"2@stanislas-XPS-13-9343"} 
[2020-02-04 14:08:10] glpisqllog.ERROR: DBmysql::query() in /home/stanislas/Teclib/dev/GLPI/9.4-bugfixes/inc/dbmysql.class.php line 188
  *** MySQL query error:
  SQL: SELECT `id` FROM `glpi_plugin_formcreator_questions` WHERE `plugin_formcreator_sections_id` = '2' ORDER BY `order` ASC
  Error: Unknown column 'order' in 'order clause'
  Backtrace :
  inc/dbmysqliterator.class.php:95                   
  inc/dbmysql.class.php:580                          DBmysqlIterator->execute()
  plugins/formcreator/inc/question.class.php:1063    DBmysql->request()
  plugins/formcreator/inc/question.class.php:177     PluginFormcreatorQuestion->getQuestionsFromSection()
  plugins/formcreator/inc/question.class.php:121     PluginFormcreatorQuestion::showForForm()
  inc/commonglpi.class.php:485                       PluginFormcreatorQuestion::displayTabContentForItem()
  ajax/common.tabs.php:92                            CommonGLPI::displayStandardTab()
  {"user":"2@stanislas-XPS-13-9343"} 

```

**Comment by btry** [comment]
Hi

I'm suspecting your branch is not up to date. In PrepareInputForAdd() is called PluginFormcreatorCommon::getMax(). An argument of this call is probably "order" in your copy, but should be "row". The correct argument is in the develop branch today.

**Comment by stonebuzz** [comment]
ok, i switch glpi to 9.4.5, and error disappears,
but, plugin continue to ask me if i  want to stay or leave this page

image

**Comment by stonebuzz** [comment]
If i leave, ticket is created

**Comment by btry** [comment]
I observed this popup, but it appears sometimes only. It seems we need to play with tabs of the page to ensure it appears. I don't have an idea why it comes here. I don't have any line of code related to that in the plugin.

**Comment by stonebuzz** [comment]
I created form with only textarea field, ive got popup each time iam try to fill form.

Beforeunlod is trigger by tinyMCE

image

**Comment by stonebuzz** [comment]
image

**Comment by btry** [comment]
This PR is important to have a proper file uploads handling with the textarea. As this issue appeared before of this PR I think the issue is not related to the change, then we may care of it on a dedicated issue, and consider to merge this fix.

**Comment by btry** [comment]
Hi
This PR is obsolete, I close it.

**Pull request closed without merging**
