### PR TITLE
Actor field

### PR DESCRIPTION
**Pull request by btry**
adds multiple users from a question to tickets

image

### CODE REVIEW

**Comment by orthagh** [comment]
your screenshot ! :+1:

**Comment by orthagh** [comment]
On my first test, here is some errors triggered by ajax requests:

```
PHP Notice: Undefined variable: entity_restrict in /var/www/html/glpi/0.91-git/ajax/getDropdownUsers.php at line 89
PHP Notice: Undefined index: searchText in /var/www/html/glpi/0.91-git/ajax/getDropdownUsers.php at line 90
```

**Comment by btry** [comment]
The feature seems to be working as expected. Notifications behave correctly.

It is ready for review. Note this branch requires the following patch https://github.com/glpi-project/glpi/pull/1231

**Comment by btry** [comment]
Backwards compatible with current release of GLPi (<= 9.1.1)

Able to use the following GLPi patches 
https://github.com/glpi-project/glpi/issues/1364
https://github.com/glpi-project/glpi/issues/1227

**Pull request merged**
