### PR TITLE
To avoid PHP notice

### PR DESCRIPTION
**Pull request by yllen**
http://forum.glpi-project.org/viewtopic.php?id=158109

### CODE REVIEW

**Comment by btry** [comment]
hi

Thank you, but the fix is already done in develop. 

Tis was a typo, and to avoid it I renamed the var as $soptions is error prone for my eyes

**Comment by yllen** [comment]
Are you sure?
For doing this pull request i open the file directly in code section of this github.

**Comment by btry** [comment]
Yes, I'm sure

see here 
https://github.com/pluginsGLPI/formcreator/blob/develop/inc/form_answer.class.php#L246

this fix will be available in the next release.

**Comment by yllen** [comment]
OK i understand.
Your new version is not in master branch but in develop branch.
What is master branch?

**Comment by btry** [comment]
master branch is the latest release. When a new version is released, master branch is updated, and only in this case. See git flow branching model

**Pull request closed without merging**
