### PR TITLE
Feature/redirect to form

### PR DESCRIPTION
**Pull request by xacobofg**
### Changes description

Update the pull request #2173  to be compatible with the latest version of the plugin. I also added a check during the creation or update of a form to make sure that a loop is not generated.

### Checklist

Please check if your PR fulfills the following specifications:

- [ ] Tests for the changes have been added
- [ ] Docs have been added/updated

### References

Closes #N/A

### CODE REVIEW

**Review by btry — COMMENTED** [review]
Also, the empty sql file is not up to date. This may be suficient to pass unit tests.

**Comment by xacobofg** [comment]
Hi @btry .
Sorry for taking so long to respond. I made the modifications you requested

**Comment by btry** [comment]
Hi

Unfortunately I don't have time for now to work in this PR. I see tests still fail.

The feature should be rebased onto support/2.14.0. This is the last chance to merge it : new features development will  be suspended for a while, to focus on reliability of the plugin. The version 2.14 will contain latest developments and we will keep this version alive on a long period of time.

**Comment by xacobofg** [comment]
Hi.
So I should update this branch with the changes made in 'support/2.14.0'?
Which is the file I have to modify to install the new field during the tests?

**Comment by btry** [comment]
Yes. You may try to rebase the branch locally onto support/2.14.0 and see if there are conflicts or not. If the rebase can be done without too much effort, this may be a good way of update.

**Comment by xacobofg** [comment]
Hi.
I managed to make the rebase

**Comment by btry** [comment]
Hi, Great. I'll try to work on that before the end of year. Unfortunately i'm really busy and could not handle your contribution so far.

**Comment by btry** [comment]
Hi

I'm working on your contribution. 
Here is my branch: https://github.com/btry/formcreator/tree/feature/redirect_to_form

It contains a rebase + a few commits.

**Comment by btry** [comment]
Hi

The feature has been merged with my additions. Everything has been squashed in a single commit: df970573150df894929916f17c7b09707e9ebecc

**Pull request closed without merging**
